/* Dữ liệu mẫu cho khu vực quản trị - chỉ nạp một lần vào lần truy cập đầu tiên. */

const DAY = 86400000;

function ago(days, hour = 9) {
  const date = new Date(Date.now() - days * DAY);
  date.setHours(hour, (days * 7) % 60, 0, 0);
  return date.toISOString();
}

function forward(days) {
  return new Date(Date.now() + days * DAY).toISOString().slice(0, 10);
}

export const demoBookings = [
  {
    code: "TGDEMO01",
    status: "pending",
    createdAt: ago(0, 8),
    name: "Nguyễn Minh Anh",
    phone: "0912345001",
    email: "minhanh.nguyen@gmail.com",
    tourId: 5,
    tourName: "Tour Sa Pa",
    date: forward(21),
    people: 2,
    note: "Cần xe bảy chỗ đi cùng gia đình, có thể xếp 2 phòng riêng.",
    total: 5780000,
  },
  {
    code: "TGDEMO02",
    status: "pending",
    createdAt: ago(1, 14),
    name: "Trần Thu Hà",
    phone: "0987654002",
    email: "thuha.tran@gmail.com",
    tourId: 2,
    tourName: "Tour Đà Nẵng - Hội An",
    date: forward(14),
    people: 4,
    note: "Kỷ niệm 5 năm cưới, muốn tour chậm nhẹ, nhiều thời gian tự do.",
    total: 9960000,
  },
  {
    code: "TGDEMO03",
    status: "pending",
    createdAt: ago(2, 10),
    name: "Lê Quốc Bảo",
    phone: "0901234003",
    email: "",
    tourId: 3,
    tourName: "Tour Hạ Long",
    date: forward(30),
    people: 6,
    note: "Nhóm công ty 6 người, xin báo giá hóa đơn VAT.",
    total: 11940000,
  },
  {
    code: "TGDEMO04",
    status: "confirmed",
    createdAt: ago(4, 9),
    updatedAt: ago(3, 11),
    name: "Phạm Ngọc Hân",
    phone: "0961234004",
    email: "ngoc.han@gmail.com",
    tourId: 1,
    tourName: "Tour Ninh Bình 2N1Đ",
    date: forward(10),
    people: 2,
    note: "Đã chuyển khoản 50% qua chuyển khoản.",
    total: 3180000,
  },
  {
    code: "TGDEMO05",
    status: "confirmed",
    createdAt: ago(6, 16),
    updatedAt: ago(5, 9),
    name: "Đỗ Hoàng Long",
    phone: "0356789005",
    email: "hoanglong.do@gmail.com",
    tourId: 6,
    tourName: "Tour Phú Quốc",
    date: forward(35),
    people: 4,
    note: "Nghỉ trọng vịt 2 đêm, có thể sắp xếp.",
    total: 13160000,
  },
  {
    code: "TGDEMO06",
    status: "confirmed",
    createdAt: ago(9, 13),
    updatedAt: ago(8, 10),
    name: "Vũ Khánh Linh",
    phone: "0882345006",
    email: "khanh.linh@gmail.com",
    tourId: 4,
    tourName: "Tour Đà Lạt",
    date: forward(18),
    people: 3,
    note: "Người lớn bị dị ứng hải sản, mong chuẩn bị thực đơn riêng.",
    total: 6570000,
  },
  {
    code: "TGDEMO07",
    status: "confirmed",
    createdAt: ago(13, 15),
    updatedAt: ago(12, 9),
    name: "Hoàng Thị Mai",
    phone: "0972345007",
    email: "thimai.hoang@gmail.com",
    tourId: 2,
    tourName: "Tour Đà Nẵng - Hội An",
    date: forward(24),
    people: 2,
    note: "",
    total: 4980000,
  },
  {
    code: "TGDEMO08",
    status: "cancelled",
    createdAt: ago(16, 11),
    updatedAt: ago(15, 14),
    name: "Bùi Tuấn Kiệt",
    phone: "0911111008",
    email: "tuan.kiet@gmail.com",
    tourId: 5,
    tourName: "Tour Sa Pa",
    date: forward(7),
    people: 2,
    note: "Khách đổi lịch công tác, xin dời sang kỳ sau.",
    total: 5780000,
  },
  {
    code: "TGDEMO09",
    status: "confirmed",
    createdAt: ago(19, 9),
    updatedAt: ago(18, 10),
    name: "Phan Kim Ngân",
    phone: "0932222009",
    email: "kimngan.phan@gmail.com",
    tourId: 3,
    tourName: "Tour Hạ Long",
    date: forward(40),
    people: 2,
    note: "Có trẻ em 6 tuổi đi cùng.",
    total: 3980000,
  },
  {
    code: "TGDEMO10",
    status: "confirmed",
    createdAt: ago(23, 17),
    updatedAt: ago(22, 8),
    name: "Đặng Thanh Tùng",
    phone: "0943333010",
    email: "thanh.tung@gmail.com",
    tourId: 1,
    tourName: "Tour Ninh Bình 2N1Đ",
    date: forward(12),
    people: 5,
    note: "Nhóm 5 người lớn, có 1 em tập xe đạp.",
    total: 7950000,
  },
  {
    code: "TGDEMO11",
    status: "confirmed",
    createdAt: ago(28, 10),
    updatedAt: ago(27, 9),
    name: "Vân Anh Thư",
    phone: "0964444011",
    email: "anhthu.van@gmail.com",
    tourId: 4,
    tourName: "Tour Đà Lạt",
    date: forward(28),
    people: 2,
    note: "",
    total: 4380000,
  },
  {
    code: "TGDEMO12",
    status: "cancelled",
    createdAt: ago(33, 14),
    updatedAt: ago(32, 16),
    name: "Trương Quốc Dũng",
    phone: "0905555012",
    email: "quocdung@gmail.com",
    tourId: 6,
    tourName: "Tour Phú Quốc",
    date: forward(15),
    people: 2,
    note: "Huỷ do visa chậm.",
    total: 6580000,
  },
  {
    code: "TGDEMO13",
    status: "confirmed",
    createdAt: ago(41, 9),
    updatedAt: ago(40, 11),
    name: "Ngô Bích Ngọc",
    phone: "0976666013",
    email: "bichngoc.ngo@gmail.com",
    tourId: 2,
    tourName: "Tour Đà Nẵng - Hội An",
    date: forward(45),
    people: 3,
    note: "Sau khi đi chuyến Sài Gòn - Nha Trang.",
    total: 7470000,
  },
  {
    code: "TGDEMO14",
    status: "confirmed",
    createdAt: ago(52, 15),
    updatedAt: ago(51, 10),
    name: "Lê Thanh Sơn",
    phone: "0987777014",
    email: "thanhson.le@gmail.com",
    tourId: 5,
    tourName: "Tour Sa Pa",
    date: forward(52),
    people: 2,
    note: "",
    total: 5780000,
  },
  {
    code: "TGDEMO15",
    status: "confirmed",
    createdAt: ago(64, 11),
    updatedAt: ago(63, 9),
    name: "Mai Thị Hồng Vân",
    phone: "0938888015",
    email: "hongvan.mai@gmail.com",
    tourId: 1,
    tourName: "Tour Ninh Bình 2N1Đ",
    date: forward(60),
    people: 6,
    note: "Đoàn khách đoàn học sinh trường THCS.",
    total: 9540000,
  },
  {
    code: "TGDEMO16",
    status: "cancelled",
    createdAt: ago(75, 16),
    updatedAt: ago(74, 10),
    name: "Hà Gia Huy",
    phone: "0919999016",
    email: "gia.huy@gmail.com",
    tourId: 3,
    tourName: "Tour Hạ Long",
    date: forward(20),
    people: 4,
    note: "Khách chuyển sang đi cùng công ty.",
    total: 7960000,
  },
  {
    code: "TGDEMO17",
    status: "confirmed",
    createdAt: ago(88, 9),
    updatedAt: ago(87, 14),
    name: "Trịnh Bảo Châu",
    phone: "0951111017",
    email: "baochau.trinh@gmail.com",
    tourId: 4,
    tourName: "Tour Đà Lạt",
    date: forward(70),
    people: 2,
    note: "",
    total: 4380000,
  },
  {
    code: "TGDEMO18",
    status: "confirmed",
    createdAt: ago(102, 13),
    updatedAt: ago(101, 9),
    name: "Phan Quang Vinh",
    phone: "0962222018",
    email: "quangvinh.phan@gmail.com",
    tourId: 2,
    tourName: "Tour Đà Nẵng - Hội An",
    date: forward(78),
    people: 2,
    note: "Đã đặt vé máy bay khứ hồi riêng.",
    total: 4980000,
  },
];

export const demoMessages = [
  {
    id: "ms1",
    name: "Nguyễn Thị Lan Anh",
    phone: "0912345001",
    email: "lananh.nguyen@gmail.com",
    topic: "Đặt tour nhóm lớn",
    message:
      "Công ty mình có 35 nhân viên muốn đi Nha Trang 4N3Đ vào cuối tháng 12. Bên mình có thể báo giá tour trọn gói gồm vé máy bay, khách sạn 4 sao và ăn uống không? Xin gửi bảng giá chi tiết theo số người.",
    read: false,
    createdAt: ago(0, 7),
  },
  {
    id: "ms2",
    name: "Trần Minh Tuấn",
    phone: "0908765432",
    email: "minhtuan.tran@gmail.com",
    topic: "Tư vấn tour",
    message:
      "Tour Sa Pa mùa lúa chín có lịch trình chi tiết ngày 1, ngày 2 thế nào? Mình dự định đi 2 người vào khoảng 20/10. Ngoài ra tour có bao gồm cắm trại đêm ở Mù Cang Chải không?",
    read: false,
    createdAt: ago(0, 16),
  },
  {
    id: "ms3",
    name: "Phạm Quốc Việt",
    phone: "0976543210",
    email: "quocviet.pham@gmail.com",
    topic: "Hợp đồng doanh nghiệp",
    message:
      "Bên tôi muốn ký hợp đồng đặt tour thường xuyên cho khách hàng doanh nghiệp với số lượng lớn. Vui lòng gửi hồ sơ năng lực và biểu mẫu hợp đồng để bên tôi xem xét.",
    read: true,
    createdAt: ago(3, 10),
  },
  {
    id: "ms4",
    name: "Lê Thị Hồng Nhung",
    phone: "0932123456",
    email: "hongnung.le@gmail.com",
    topic: "Góp ý/khiếu nại",
    message:
      "Chuyến Hạ Long hôm 12/10 nhà xe đến trễ gần 1 tiếng so với lịch, làm ảnh hưởng lịch tham quan ở đảo. Mong bên mình giải trình và bồi thường giúp nhóm mình bữa trưa tại nhà hàng địa phương.",
    read: false,
    createdAt: ago(5, 14),
  },
  {
    id: "ms5",
    name: "Đỗ Trung Kiên",
    phone: "0987654321",
    email: "trungkien.do@gmail.com",
    topic: "Tư vấn tour",
    message:
      "Gia đình 6 người (2 người lớn, 4 trẻ em) muốn đi Phú Quốc tháng 11. Tour 3N2Đ có phòng đôi cho 3 người lớn và phòng gia đình cho 4 em không? Tổng chi phí khoảng bao nhiêu?",
    read: true,
    createdAt: ago(9, 11),
  },
  {
    id: "ms6",
    name: "Hoàng Anh Tú",
    phone: "0912345999",
    email: "anhtu.hoang@gmail.com",
    topic: "Đặt tour nhóm lớn",
    message:
      "Tôi cần đặt 12 suất tour Hạ Long cho khách hàng thân thiết vào ngày 15/11. Có chương trình ưu đãi cho nhóm từ 10 người trở lên không? Thanh toán được bằng chuyển khoản doanh nghiệp.",
    read: true,
    createdAt: ago(15, 15),
  },
  {
    id: "ms7",
    name: "Nguyễn Thu Trang",
    phone: "0967777888",
    email: "thutrang.nguyen@gmail.com",
    topic: "Góp ý/khiếu nại",
    message:
      "Ảnh trên website tour Đà Lạt khác thực tế một chút. Tôi thấy điểm đến cuối tuần khá đông, mong thêm thông tin về thời điểm nào đi ít khách nhất.",
    read: true,
    createdAt: ago(22, 9),
  },
  {
    id: "ms8",
    name: "Vũ Đình Cường",
    phone: "0938888999",
    email: "dinhuong.vu@gmail.com",
    topic: "Tư vấn tour",
    message:
      "Tour Ninh Bình 2N1Đ có điểm dừng Tràng An - Vân Long không? Thời gian tham quan bao lâu và có đi bộ bao xa? Mình có 2 cháu nhỏ 5 và 8 tuổi nên hơi lo về thể lực.",
    read: true,
    createdAt: ago(31, 17),
  },
];

export const demoReviews = [
  {
    id: "rv1",
    tourId: 1,
    author: "Nguyễn Minh Anh",
    rating: 5,
    content:
      "Cảnh Tràng An đẹp hơn ảnh, hướng dẫn viên nhiệt tình, đồ ăn hợp khẩu vị. Chắc chắn sẽ quay lại lần nữa.",
    status: "pending",
    createdAt: ago(1, 20),
  },
  {
    id: "rv2",
    tourId: 2,
    author: "Vũ Khánh Linh",
    rating: 4,
    content:
      "Tour Đà Nẵng Hội An đi nhanh hơn mình mong đợi, cần thêm buổi tự do ở Hội An. Nhưng khách sạn và xe đều ổn.",
    status: "pending",
    createdAt: ago(2, 11),
  },
  {
    id: "rv3",
    tourId: 3,
    author: "Phan Kim Ngân",
    rating: 5,
    content:
      "Vịnh Hạ Long buổi sáng đẹp nhất, thuyền riêng nhóm 2 người rất riêng tư. Cảm ơn bạn Hà của TravelGo đã hỗ trợ nhiệt tình.",
    status: "approved",
    createdAt: ago(6, 8),
  },
  {
    id: "rv4",
    tourId: 5,
    author: "Trần Thu Hà",
    rating: 5,
    content:
      "Mùa lúa chín tuyệt vời, homestay ở Tà Xiêng ấm cúng. Giá hợp lý so với chất lượng.",
    status: "approved",
    createdAt: ago(11, 14),
  },
  {
    id: "rv5",
    tourId: 4,
    author: "Vân Anh Thư",
    rating: 3,
    content:
      "Xe đi từ Hà Nội dừng nghỉ 2 lần dài, làm giãm thời gian tham quan Cầu Đất. Tuy nhiên nhà nghỉ và ăn uống đều được.",
    status: "approved",
    createdAt: ago(18, 19),
  },
  {
    id: "rv6",
    tourId: 6,
    author: "Đỗ Hoàng Long",
    rating: 2,
    content: "Chuyến đi bị trễ 1 tiếng mà không có ai thông báo. Chất lượng dịch vụ chưa tốt.",
    status: "rejected",
    createdAt: ago(20, 10),
  },
  {
    id: "rv7",
    tourId: 2,
    author: "Mai Thị Hồng Vân",
    rating: 5,
    content:
      "Bàu trời thời tiết tốt, Đà Nẵng sạch đẹp. Resort ven biển đúng như ảnh, nhân viên hỗ trợ nhiệt tình.",
    status: "pending",
    createdAt: ago(4, 12),
  },
  {
    id: "rv8",
    tourId: 1,
    author: "Trịnh Bảo Châu",
    rating: 4,
    content: "Lịch trình hợp lý, giá tour tốt. Chỉ tiếc thời tiết hôm đó trở mưa nên ảnh không đẹp bằng.",
    status: "approved",
    createdAt: ago(26, 16),
  },
];

export const demoCoupons = [
  {
    id: "cp1",
    code: "CHAOBAN10",
    type: "percent",
    value: 10,
    minTotal: 3000000,
    maxDiscount: 500000,
    usageLimit: 100,
    usedCount: 34,
    startDate: forward(-20),
    endDate: forward(40),
    active: true,
    description: "Giảm 10% cho đơn từ 3 triệu, tối đa 500k.",
  },
  {
    id: "cp2",
    code: "WELCOME500K",
    type: "fixed",
    value: 500000,
    minTotal: 5000000,
    maxDiscount: 0,
    usageLimit: 200,
    usedCount: 87,
    startDate: forward(-60),
    endDate: forward(90),
    active: true,
    description: "Giảm ngay 500k cho khách hàng mới đặt tour từ 5 triệu.",
  },
  {
    id: "cp3",
    code: "SAPA15",
    type: "percent",
    value: 15,
    minTotal: 2000000,
    maxDiscount: 800000,
    usageLimit: 50,
    usedCount: 50,
    startDate: forward(-30),
    endDate: forward(5),
    active: true,
    description: "Ưu đãi mùa lúa chín tuyến Sa Pa.",
  },
  {
    id: "cp4",
    code: "GIAMNHA",
    type: "fixed",
    value: 300000,
    minTotal: 2000000,
    maxDiscount: 0,
    usageLimit: 300,
    usedCount: 121,
    startDate: forward(-120),
    endDate: forward(150),
    active: true,
    description: "Giảm 300k cho mọi đơn từ 2 triệu.",
  },
  {
    id: "cp5",
    code: "TET2025",
    type: "percent",
    value: 20,
    minTotal: 5000000,
    maxDiscount: 1500000,
    usageLimit: 30,
    usedCount: 0,
    startDate: forward(60),
    endDate: forward(150),
    active: false,
    description: "Ưu đãi dịp Tết, chưa kích hoạt.",
  },
  {
    id: "cp6",
    code: "HAGIANG20",
    type: "percent",
    value: 20,
    minTotal: 2500000,
    maxDiscount: 900000,
    usageLimit: 40,
    usedCount: 38,
    startDate: forward(-15),
    endDate: forward(25),
    active: true,
    description: "Ưu đãi tuyến Hà Giang mùa hoa ban.",
  },
];

export const demoLogs = [
  { id: "lg1", user: "Trịnh Minh Vũ", action: "Cập nhật tour", detail: "Thay đổi giá tour Ninh Bình 2N1Đ lên 1.590.000đ", createdAt: ago(0, 7) },
  { id: "lg2", user: "Trịnh Minh Vũ", action: "Đăng nhập", detail: "Đăng nhập hệ thống từ trình duyệt Chrome", createdAt: ago(0, 6) },
  { id: "lg3", user: "Hà Quốc Việt", action: "Xác nhận đơn", detail: "Xác nhận đơn TGDEMO04 - Nguyễn Minh Anh", createdAt: ago(1, 9) },
  { id: "lg4", user: "Bùi Đức Hiệp", action: "Duyệt đánh giá", detail: "Duyệt đánh giá 5 sao cho tour Hạ Long", createdAt: ago(2, 14) },
  { id: "lg5", user: "Hà Quốc Việt", action: "Tạo mã giảm giá", detail: "Tạo mã HAGIANG20 giảm 20%", createdAt: ago(4, 11) },
  { id: "lg6", user: "Trịnh Minh Vũ", action: "Cập nhật cấu hình", detail: "Sửa thông tin liên hệ hotline", createdAt: ago(6, 16) },
  { id: "lg7", user: "Bùi Đức Hiệp", action: "Xoá đơn", detail: "Xoá đơn TGDEMO16 sau khi khách huỷ", createdAt: ago(8, 10) },
  { id: "lg8", user: "Trịnh Minh Vũ", action: "Tạo tài khoản", detail: "Tạo tài khoản nhanvien với vai trò Nhân viên", createdAt: ago(12, 8) },
  { id: "lg9", user: "Hà Quốc Việt", action: "Huỷ đơn", detail: "Huỷ đơn TGDEMO08 - Vũ Khánh Linh", createdAt: ago(15, 13) },
  { id: "lg10", user: "Trịnh Minh Vũ", action: "Khôi phục dữ liệu", detail: "Khôi phục danh sách tour về dữ liệu gốc", createdAt: ago(20, 15) },
];

export const demoNotes = [
  { phone: "0912345001", note: "Khách VIP, đã đi 3 chuyến. Ưu tiên hỗ trợ nhanh.", createdAt: ago(10, 9) },
  { phone: "0987654002", note: "Doanh nghiệp vừa, có thể đề xuất hợp đồng tour nhóm.", createdAt: ago(6, 14) },
  { phone: "0901234003", note: "Yêu cầu hóa đơn VAT, liên hệ kế toán trước khi chốt.", createdAt: ago(3, 11) },
];
